# Generated by Django 3.0.8 on 2020-07-15 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200715_0359'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.TextField(default='Dummy Data', max_length=20),
            preserve_default=False,
        ),
    ]
