# Generated by Django 3.0.8 on 2020-07-15 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.TextField(default='I made this later, bear w me', max_length=30),
            preserve_default=False,
        ),
    ]
